on: [push]

jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run Terrascan
      id: terrascan
      uses: tenable/terrascan-action@job-summary
      #uses: robermp/terrascan-action@feature/add_outputs
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'aws'
        only_warn: true
        verbose: false
#        sarif_upload: true
#    - name: Upload SARIF file
#      uses: github/codeql-action/upload-sarif@v1
#      with:
#        sarif_file: terrascan.sarif
    - name: Comment on PR
      uses: harupy/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        template: scan-result.txt
#    - name: Comment on PR
#      uses: actions/github-script@0.9.0
#      #if: github.event_name == 'pull_request'
#      env:
#        terrascan_log: "${{ steps.terrascan.outputs.result }}"
#        terrascan_err: "${{ steps.terrascan.outputs.err }}"
#      with:
#        github-token: ${{ secrets.GITHUB_TOKEN }}
#        script: |
#          ${ terrascan_result } Terrascan Validation
